Installer detection improvements
Trenly/winget-pkgs pull request #111
Opened 2021-11-18 02:34 UTC by Trenly

@jedieaston @OfficialEsco  

Making some big changes to how the installer entry is built out for new manifests. If you wouldn't mind doing some testing, I'm not sure how stable it is. I think it works, but I haven't gone through every possible use case

2021-11-18 09:19 UTC, OfficialEsco commented
Oooo found a issue when creating a new package, the ProductCode field is not removed when no ProductCode is enterted
```
  ProductCode: ""
```

Also, we should probably clear the `ReleaseNotes` and `ReleaseNotesUrl` field

2021-11-18 09:21 UTC, Trenly commented
> Oooo found a issue when creating a new package, the ProductCode field is not removed when no ProductCode is enterted
> 
> ```
>   ProductCode: ""
> ```
> 
> Also, we should probably clear the `ReleaseNotes` and `ReleaseNotesUrl` field

I've got a separate branch going for release notes things; I'll merge that into this one and try and fix that product code issue

2021-11-18 09:24 UTC, OfficialEsco commented
> I've got a separate branch going for release notes things; I'll merge that into this one

We don't actually have any `ReleaseNote` or `ReleaseNotesUrl` metadata tho, so i don't think its too critical, better to merge it when we can input the metadata

Also the `ReleaseNotes` field sounds scary working with in Powershell

2021-11-18 09:26 UTC, Trenly commented
> > I've got a separate branch going for release notes things; I'll merge that into this one
> 
> We don't actually have any `ReleaseNote` or `ReleaseNotesUrl` metadata tho, so i don't think its too critical, better to merge it when we can input the metadata
> 
> Also the `ReleaseNotes` field sounds scary working with in Powershell

It shouldn't be too bad honestly. Its just a string value thats up to 10k characters with multiline support

I'm more worried about ReleaseDate, since that is just a date. Do you know if there is a specific format needed for that? I'm thinking its just yyyy-MM-dd but I'm not 100% sure

2021-11-18 09:31 UTC, OfficialEsco commented
> I'm more worried about ReleaseDate, since that is just a date. Do you know if there is a specific format needed for that? I'm thinking its just yyyy-MM-dd but I'm not 100% sure

```
"ReleaseDate": {
      "type": [ "string", "null" ],
      "format": "date",
      "description": "The installer release date"
    }
```

Quick testing shows ANYTHING is valid, but we should use (tbh force) yyyy-MM-dd yes

2021-11-18 09:33 UTC, Trenly commented
> > I'm more worried about ReleaseDate, since that is just a date. Do you know if there is a specific format needed for that? I'm thinking its just yyyy-MM-dd but I'm not 100% sure
> 
> ```
> "ReleaseDate": {
>       "type": [ "string", "null" ],
>       "format": "date",
>       "description": "The installer release date"
>     }
> ```
> 
> Quick testing shows ANYTHING is valid, but we should use (tbh force) yyyy-MM-dd yes

Perfect; I have it set up (again, different branch) to try and parse whatever the user enters into that format. So they could enter December 30 2021 and it should parse the value to 2021-12-30

2021-11-18 13:26 UTC, jedieaston commented
BTW, the `format: date` means that the date has to be ISO8601, i.e. `yyyy-MM-dd`. https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times.

2021-11-18 13:30 UTC, OfficialEsco commented
> BTW, the `format: "date"` means that the date has to be ISO8601, i.e. `yyyy-MM-dd`. https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times.

makes sense, seems like winget version 1.2.3131 can't validate it correctly then, cuz i could type anything and it would pass 🤷‍♂️

2021-11-18 14:15 UTC, OfficialEsco commented
Got another bug when creating a new package with 2 installers, https://github.com/microsoft/winget-pkgs/pull/35217

The script didn’t ask for the unknown archietecture so it just used x64

2021-11-18 15:44 UTC, Trenly commented
> Got another bug when creating a new package with 2 installers, [microsoft#35217](https://github.com/microsoft/winget-pkgs/pull/35217)
> 
> The script didn’t ask for the unknown archietecture so it just used x64

I haven’t looked fully yet, but it seems like this would occur even when on microsoft/master because the packageidentifier has 64 in it?

2021-11-18 15:48 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +    if ($URI -match '\b(x|win){0,1}64\b') { return 'x64' }
Yeeeeah that sounds about right, guess its a rare issue

2021-11-18 15:52 UTC, Trenly commented on Tools/YamlCreate.ps1
> +    if ($URI -match '\b(x|win){0,1}64\b') { return 'x64' }
Yep; Thats exactly the line I was thinking of.

I think theres three options here, and I don’t know which is best -
1) Do nothing and treat it as an edge case
2) Ask the user to confirm every time
3) Remove automatic detection

I’m open to discussion on what others think is best

2021-11-18 15:59 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +    if ($URI -match '\b(x|win){0,1}64\b') { return 'x64' }
I would like to go with option 2.

2021-11-18 16:03 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +    if ($URI -match '\b(x|win){0,1}64\b') { return 'x64' }
option 2 would probably be best ye, we rarely actually use option 1 now so we won't be seeing that question often
(when adding more installers its a lot faster to copy paste -> replace/find and replace links -> run -AutoUpgrade)

2021-11-18 16:08 UTC, Trenly commented on Tools/YamlCreate.ps1
> +    if ($URI -match '\b(x|win){0,1}64\b') { return 'x64' }
I’ll make the changes to have users confirm the architecture when using the interactive mode. 

I do have a test branch in progress for using an object to update packages, which would allow you to basically skip the step of manual copying and editing. It is based off of this branch though, so I’d like to make sure this one is stable before bringing in those changes. If you’d like to see more about it - https://github.com/Trenly/winget-pkgs/commit/dbaf260712dfaf5e15b51131dcb145a99aed516c#commitcomment-60474729

2021-11-18 17:01 UTC, jedieaston commented
I know it's not relevant to this PR, but just wanted to let y'all know re date validation: https://github.com/microsoft/winget-cli/issues/1725

2021-11-18 17:05 UTC, Trenly commented on Tools/YamlCreate.ps1
> +    if ($URI -match '\b(x|win){0,1}64\b') { return 'x64' }
Resolved in https://github.com/Trenly/winget-pkgs/pull/111/commits/5074e136ec1b41e2ae4c84a54d32fb0a07fc6066

2021-11-19 04:33 UTC, vedantmgoyal2009 commented
@Trenly Does 9e74f09fe59cc4e91a2d5aaeb6ffb1c16a87515a resolves https://github.com/Trenly/winget-pkgs/issues/28?

2021-11-19 04:44 UTC, Trenly commented
> @Trenly Does [9e74f09](https://github.com/Trenly/winget-pkgs/commit/9e74f09fe59cc4e91a2d5aaeb6ffb1c16a87515a) resolves #28?

Almost; I still have to figure out the auto update, but yes

2021-11-19 12:16 UTC, vedantmgoyal2009 requested changes
Typo and Color

2021-11-19 12:16 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            Write-Host "Matching Installer Foud"
```suggestion
            Write-Host "`nMatching Installer Found" -ForegroundColor Yellow
```

2021-11-19 13:58 UTC, jedieaston commented on Tools/YamlCreate.ps1
> +            Write-Host "Matching Installer Foud"
Why the newline?

2021-11-19 14:07 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +            Write-Host "Matching Installer Foud"
How on earth do i trigger this Write-Host?
I keep seeing
```
Selection: 1

[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>. For example: Microsoft.Excel
PackageIdentifier: 64Gram.64Gram2

[Required] Enter the version. for example: 1.33.7
Version: 1.0.1

[Required] Enter the download url to the installer.
Url: https://github.com/TDesktop-x64/tdesktop/releases/download/v1.0.1/64Gram-setup.1.0.1.exe


Downloading URL. This will take a while...
Time taken: 2 second(s)

[Optional] Enter the architecture. Options: x86, x64, arm, arm64, neutral
Old Variable: x64
Architecture:
```
(which needs to be updated)

2021-11-19 14:08 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            Write-Host "Matching Installer Foud"
I think it looks better, however, if you don't like it, feel free to remove it.

2021-11-19 16:27 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            Write-Host "Matching Installer Foud"
That line was only for my testing anyways, since its easier than going into the script debugger.

2021-11-22 09:11 UTC, OfficialEsco approved these changes
Pretty sure this is approvable at this state 🤔 Unless you want to do more

2021-11-22 12:26 UTC, merged