fix: git add command
Trenly/winget-pkgs pull request #162
Opened 2022-03-12 13:18 UTC by vedantmgoyal2009

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-13 00:20 UTC, Trenly commented
cc @jedieaston @OfficialEsco

2022-03-13 18:07 UTC, jedieaston reviewed
It may be better to use `git rev-parse --show-toplevel` to get the path, as that doesn’t rely on YamlCreate itself staying in the same place, just that it is in the repo somewhere.  

https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---show-toplevel

2022-03-15 15:31 UTC, jedieaston approved these changes

2022-03-15 21:22 UTC, jedieaston commented
I would. It makes it more reliable.

2022-03-15 23:33 UTC, Trenly requested changes
https://github.com/Trenly/winget-pkgs/pull/162#issuecomment-1068385615

2022-03-19 04:25 UTC, Trenly requested changes
This is going to be a very nit-picky comment, so apologies in advance.

-----
I know that showing the toplevel isn't a compute-intensive command, but given that you are using the script for automation, it would be better to only fetch it once. If you add this at the beginning of the script, then you should be able to use the suggestions below
```
$script:gitTopLevel = (Resolve-Path $(git rev-parse --show-toplevel)).Path
```
Also, `Test-Path` and `Resolve-Path` are volatile functions when used with `git-rev-parse --show-toplevel` because the rev-parse will return null when the user is not in a git repository. ***There should be a Try-Catch block for these commands***. If you take the suggestion above, at the top of the script you can do something like this to avoid needing multiple try-catch
```powershell
try { 
  $script:gitTopLevel = (Resolve-Path $(git rev-parse --show-toplevel)).Path
}
catch { 
  # If there was an exception, the user isn't in a git repo. Throw a custom exception and pass the original exception as an InternalException
  throw [UnmetDependencyException]::new("This script must be run from inside a clone of the winget-pkgs repository", $_.Exception)
}
```

2022-03-19 04:25 UTC, Trenly commented on Tools/YamlCreate.ps1
> +                $SandboxScriptPath = (Resolve-Path "$(git rev-parse --show-toplevel)\Tools\SandboxTest.ps1").Path
```suggestion
            if (Test-Path -Path "$gitTopLevel\Tools\SandboxTest.ps1") {
                $SandboxScriptPath = (Resolve-Path "$gitTopLevel\Tools\SandboxTest.ps1").Path
```

2022-03-19 04:25 UTC, Trenly commented on Tools/YamlCreate.ps1
> +        git add "$((Resolve-Path "$(git rev-parse --show-toplevel)/manifests").Path)\*"
```suggestion
        git add "$((Resolve-Path "$gitTopLevel/manifests").Path)\*"
```

2022-03-19 04:25 UTC, Trenly commented on Tools/YamlCreate.ps1
> +                Read-PRBody (Resolve-Path "$(git rev-parse --show-toplevel)\.github\PULL_REQUEST_TEMPLATE.md").Path
```suggestion
            if (Test-Path -Path "$gitTopLevel\.github\PULL_REQUEST_TEMPLATE.md") {
                Read-PRBody (Resolve-Path "$gitTopLevel\.github\PULL_REQUEST_TEMPLATE.md").Path
```

2022-03-19 05:02 UTC, Trenly approved these changes
Remaining comments are nits; I'll wait for @jedieaston to take a look too

2022-03-19 05:02 UTC, Trenly commented on Tools/YamlCreate.ps1
> +
If you wanted to be really sneaky, this could be moved all the way up, even before the check for powershell-yaml, since it doesn't pay to download the dependencies or create the settings file if they aren't running in a clone of the repo

2022-03-20 04:27 UTC, jedieaston approved these changes
LGTM. I think those nits are valid though.

2022-03-20 17:05 UTC, merged