Add Custom Error Class
Trenly/winget-pkgs pull request #18
Opened 2021-08-18 05:20 UTC by Trenly

@OfficialEsco I haven't gotten it finished yet, but since I was looking at validating the Installer URL from your [Comment](https://github.com/microsoft/winget-pkgs/pull/21204#discussion_r690505374) I decided to add in a custom class for us to do the error checking and feedback to users. 

Let me know what you think. If you like it, we can use this for error checking all the other fields.

2021-08-18 09:31 UTC, OfficialEsco commented
Not 100% sure what am looking at 🙄 but it does look like what i wanted 😁

2021-08-18 09:43 UTC, Trenly commented
> Not 100% sure what am looking at 🙄 but it does look like what i wanted 😁
> 
> Edit: Can also confirm it works perfectly as of now 👌 However "explaining" why the pattern is wrong might not be the smartest idea since it makes no sense 😁

That's a fair point. I obviously have to go through and do the rest of the error conditions, but do you have any suggestions as to what the message should be for invalid patterns (at least for those complex ones, I think the SHA256 pattern is pretty self explainatory) ?

2021-08-18 09:56 UTC, OfficialEsco commented
> Edit: Maybe `Invalid Pattern - The Package Identifier entered does not match the pattern requirements defined in the manifest schema` (and similar)

I think this is clear enough tbh
Even tho the InstallerSha Pattern (`^[A-Fa-f0-9]{64}$`) is short i don't actually know what it wants from me and that is probably what most people will think

Url pattern is sorta understandable, but you should understand that it fails because its not a URL (or its missing http/https

2021-08-20 17:26 UTC, Trenly commented
@OfficialEsco I pushed a few more error messages. I'm still working on the Locale Manifest section, but I think that's the last section that needs to be done

If you wouldn't mind taking this version for a few spins so I can work out any bugs

2021-08-20 17:37 UTC, OfficialEsco commented
> @OfficialEsco I pushed a few more error messages. I'm still working on the Locale Manifest section, but I think that's the last section that needs to be done
> 
> If you wouldn't mind taking this version for a few spins so I can work out any bugs

Since you are going to the Locale part, please look into the bug where the Moniker gets into the locale manifest, it creates a warning since its not "allowed" in the Schema 🙃

When i tried to find what on earth made it get in there nothing made a difference..

2021-08-20 17:47 UTC, Trenly commented
> > @OfficialEsco I pushed a few more error messages. I'm still working on the Locale Manifest section, but I think that's the last section that needs to be done
> > If you wouldn't mind taking this version for a few spins so I can work out any bugs
> 
> Since you are going to the Locale part, please look into the bug where the Moniker gets into the locale manifest, it creates a warning since its not "allowed" in the Schema 🙃
> 
> When i tried to find what on earth made it get in there nothing made a difference..

I see that it is supposed to be in the Locale Manifest?
https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json
```
    "Moniker": {
      "$ref": "#/definitions/Tag",
      "description": "The most common package term"
    },
```

I don't see any definition for it in the Installer or Version manifest schemas. Where is this error showing up?

2021-08-20 17:54 UTC, OfficialEsco commented
> I don't see any definition for it in the Installer or Version manifest schemas. Where is this error showing up?

When you do `winget validate` and the bot will throw a Warning but not fail.

Issue report: Spacing

```
Enter Choice (default is 'N'): m
[Optional] Enter the Upgrade Behavior
  [I] install
  [U] uninstallPrevious

Enter Choice (default is 'I'):
Do you want to create another installer?
  [Y] Yes
  [N] No
```

```
Have you signed the Contributor License Agreement (CLA)?
Reference Link: https://cla.opensource.microsoft.com/microsoft/winget-pkgs
  [Y] Yes
  [N] No

Enter Choice (default is 'N'): y
Have you checked that there aren't other open pull requests for the same manifest update/change?
Reference Link: https://github.com/microsoft/winget-pkgs/pulls
  [Y] Yes
  [N] No

Enter Choice (default is 'N'): y
Have you tested your manifest locally with 'winget install --manifest <path>'?
You did not test your Manifest in Windows Sandbox previously.
  [Y] Yes
  [N] No

Enter Choice (default is 'N'): n
Does your manifest conform to the 1.0 schema?
Reference Link: https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md
  [Y] Yes
  [N] No

Enter Choice (default is 'N'): y
Does this pull request resolve any issues?
  [Y] Yes
  [N] No

Enter Choice (default is 'N'): n
Warning: 1 uncommitted change
```

2021-08-20 18:00 UTC, Trenly commented
> > I don't see any definition for it in the Installer or Version manifest schemas. Where is this error showing up?
> 
> When you do `winget validate` and the bot will throw a Warning but not fail.

Seems like an issue with winget validate, since it happens with existing packages like Google Chrome that have always passed validation

2021-08-20 19:23 UTC, Trenly commented
@OfficialEsco I force updated the YamlParsing branch and this branch. Can you make sure I didn't break anything else when I did that?

2021-08-20 19:55 UTC, OfficialEsco requested changes

2021-08-20 19:55 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +    $MaxItemsInstallerSuccessCodes = $InstallerSchema.definitions.InstallerSuccessCodes.maxItems
This got back into the script
```suggestion
```

2021-08-20 20:01 UTC, OfficialEsco reviewed
Didn't get a answer, is the PackageLocale prompt intentional?

```
[Optional] List of supported installer modes. Options: interactive, silent, silentWithProgress
Old Value: interactive, silent, silentWithProgress
InstallModes:

[Required] Enter the Package Locale. For example: en-US, en-CA https://docs.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
PackageLocale: en-US

[Optional] Enter the full publisher name. For example: Microsoft Corporation
Old Variable: Malwarebytes
Publisher:

[Optional] Enter the full application name. For example: Microsoft Teams
Old Variable: Malwarebytes Privacy
PackageName:
```

2021-08-20 20:15 UTC, Trenly commented
> Didn't get a answer, is the PackageLocale prompt intentional?
> 
> ```
> [Optional] List of supported installer modes. Options: interactive, silent, silentWithProgress
> Old Value: interactive, silent, silentWithProgress
> InstallModes:
> 
> [Required] Enter the Package Locale. For example: en-US, en-CA https://docs.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
> PackageLocale: en-US
> 
> [Optional] Enter the full publisher name. For example: Microsoft Corporation
> Old Variable: Malwarebytes
> Publisher:
> 
> [Optional] Enter the full application name. For example: Microsoft Teams
> Old Variable: Malwarebytes Privacy
> PackageName:
> ```

That one isn't. I think it happened in one of my last changes. I'll look and see what happened

2021-08-20 23:46 UTC, OfficialEsco reviewed
For my normal usage 👌

Appx/MSIX path issues:

[Recommended] Enter the installer SignatureSha256
SignatureSha256: E0BB72C4EA259C621EC4666EA431BA2390C67A535C95F0B1EDE4CA97BC79BAC1

Spacing at this part
```
[Recommended] Enter the installer SignatureSha256
SignatureSha256: E0BB72C4EA259C621EC4666EA431BA2390C67A535C95F0B1EDE4CA97BC79BAC1


[Recommended] Enter the installer PackageFamilyName
  [F] Find Automatically [Note: This will install the package to find Family Name and then removes it.]
  [M] Manually Enter PackageFamilyName

Enter Choice (default is 'M'): m
[Recommended] Enter the PackageFamilyName
PackageFamilyName: )=(/!"#!"#
[Error] Invalid Pattern - The value entered does not match the pattern requirements defined in the manifest schema
```

New Locale (probably not finished here?)
Needs reference link on new line
```
[Required] Enter the Package Locale. For example: en-US, en-CA https://docs.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
PackageLocale: derp
[Error] Invalid Length - Length must be between 1 and 20 characters
```

2021-08-21 15:08 UTC, Trenly commented
> For my normal usage 👌
> 
> Appx/MSIX path issue:
> 
> Spacing at this part
> 
> ```
> [Recommended] Enter the installer SignatureSha256
> SignatureSha256: E0BB72C4EA259C621EC4666EA431BA2390C67A535C95F0B1EDE4CA97BC79BAC1
> 
> 
> [Recommended] Enter the installer PackageFamilyName
>   [F] Find Automatically [Note: This will install the package to find Family Name and then removes it.]
>   [M] Manually Enter PackageFamilyName
> 
> Enter Choice (default is 'M'): m
> [Recommended] Enter the PackageFamilyName
> PackageFamilyName: )=(/!"#!"#
> [Error] Invalid Pattern - The value entered does not match the pattern requirements defined in the manifest schema
> ```
> 
> New Locale (probably not finished here?)
> Needs reference link on new line
> 
> ```
> [Required] Enter the Package Locale. For example: en-US, en-CA https://docs.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
> PackageLocale: derp
> [Error] Invalid Length - Length must be between 1 and 20 characters
> ```

Okay, I think these are fixed

2021-08-21 16:33 UTC, OfficialEsco reviewed
I just created a manifest and accedently had capslock on which reminded me some of the enum's are case-sensitive
In my case `Architecture`

```
Manifest validation failed.
Manifest Error: Schema validation failed.
Error context: <root>[Installers][0][Architecture] Description: Failed to match against any enum values.
Error context: <root>[Installers][0] Description: Failed to validate against schema associated with property name 'Architecture'.
Error context: <root>[Installers] Description: Failed to validate item #0 in array.
Error context: <root> Description: Failed to validate against schema associated with property name 'Installers'.
 File: altair-graphql.altair.installer.yaml
```

2021-08-21 16:50 UTC, OfficialEsco reviewed
New Locale looks 👌
Still this scary warning tho..

```
Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\v\VivaldiTechnologies\Vivaldi\4.1.2369.21\VivaldiTechnologies.Vivaldi.locale.nb-NO.yaml
Manifest validation succeeded with warnings.
Manifest Warning: Unknown field. Field: Moniker
```

2021-08-21 16:50 UTC, OfficialEsco approved these changes

2021-08-21 17:01 UTC, OfficialEsco reviewed
~~Weird, now that i ONLY created a Locale moniker did not get added~~

~~It prompted for it and displayed the en-US moniker~~
```
[Optional] Enter the Moniker (friendly name/alias). For example: vscode
Old Variable: opera
Moniker:
```

~~But it did not get added to the Manifest~~

```
Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\o\Opera\Opera\78.0.4093.147\Opera.Opera.locale.nb-NO.yaml
Manifest validation succeeded.
```

![image](https://user-images.githubusercontent.com/15158490/130329471-41143313-25ee-41bd-a430-4d2d7c5676a5.png)

My dumb ass was on the wrong branch again.

2021-08-21 17:26 UTC, Trenly commented
I’ll see if I can make the enums case sensitive. Do you know which ones are?

I’ll look more into the warning. Its very strange.

Was the issue with Moniker just you being on the wrong branch, or do I need to look at something more

2021-08-21 17:36 UTC, OfficialEsco commented
> I’ll see if I can make the enums case sensitive. Do you know which ones are?

I think it might actually be all of them

> I’ll look more into the warning. Its very strange.

Yeah not sure since it says `Unknown field` when its clearly in the schema...

> Was the issue with Moniker just you being on the wrong branch, or do I need to look at something more

Yup, just a me issue 🤦‍♂️

2021-08-23 04:01 UTC, Trenly commented
> > I’ll see if I can make the enums case sensitive. Do you know which ones are?
> 
> I think it might actually be all of them

This should be fixed now
 
> > I’ll look more into the warning. Its very strange.
> 
> Yeah not sure since it says `Unknown field` when its clearly in the schema...

Do you think we should open an issue in winget-cli to see if it is something that we are doing wrong with the powershell script, or if it is something wrong on their end? Does this happen with the main [YamlParsing](/Trenly/winget-pkgs/tree/YamlParsing) branch too?

2021-08-23 06:37 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
Would it be hard to implement select unique for File extensions? Because its VERY HARD to find the duplicate in 50 items

2021-08-23 06:46 UTC, OfficialEsco commented
> Do you think we should open an issue in winget-cli to see if it is something that we are doing wrong with the powershell script, or if it is something wrong on their end? Does this happen with the main YamlParsing branch too? 

Feel free to do that, however the bot also see the Moniker as a Warning.

From my POV it looks like Moniker is not a valid  variable but a Reference.

The only part the script has in this that it adds the Moniker because the local schema says its valid.

2021-08-23 13:14 UTC, Trenly commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
I don’t think it would be, but I can check

2021-08-23 13:15 UTC, Trenly commented
> From my POV it looks like Moniker is not a valid variable but a Reference.
> 
I guess I’m still a bit confused as to what you mean by this

2021-08-23 13:17 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
AFAIK you can probably do `$FileExtensions | Select-Object -Unique` somewhere

2021-08-23 13:26 UTC, Trenly commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
No,  it isn't quite that simple because we are handling everything as a string. However, after looking at it again, I am 99% sure I already implemented this in line 739 in the updated files.

2021-08-23 13:30 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
O, you might be correct, i’ve actually not tested it, i just remember you saying it but not saying you implemented it 🤦‍♂️

2021-08-23 19:18 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
Well, good thing i brought that up 😁

```
[Optional] Enter any tags that would be useful to discover this tool.
Example: zip, c++, photos, OBS (Max 16 items)
Old Variable: strategy, game, tactical, fantasy, turn-based, multiplayer, singleplayer
Tags: strategy, game, tactical, fantasy, turn-based, multiplayer, singleplayer, singleplayer 
```

```
Manifest validation failed.
Manifest Error: Schema validation failed.
Error context: <root>[Tags] Description: Elements at indexes #6 and #7 violate uniqueness constraint.
Error context: <root> Description: Failed to validate against schema associated with property name 'Tags'.
 File: Wesnoth.BattleForWesnoth.locale.en-US.yaml
```

![image](https://user-images.githubusercontent.com/15158490/130504918-519549d9-626a-4b44-8b7e-255224a8a581.png)

2021-08-23 22:55 UTC, Trenly commented on Tools/YamlCreate.ps1
> -    } while (($script:FileExtensions -split ",").Count -gt $Patterns.MaxItemsFileExtensions -or !([string]::IsNullOrEmpty($($script:FileExtensions -split "," | TrimString | Where-Object { -not (Strin
Looks like I'm only doing it for new values entered. I'll update it to be both new and old values that get uniqued

2021-08-23 22:55 UTC, Trenly commented
> > From my POV it looks like Moniker is not a valid variable but a Reference.
> 
> I guess I’m still a bit confused as to what you mean by this

@OfficialEsco

2021-08-24 07:54 UTC, OfficialEsco commented
> > From my POV it looks like Moniker is not a valid variable but a Reference.
> 
> I guess I’m still a bit confused as to what you mean by this

I was wrong
https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json
Both look the same so it should be valid

2021-08-24 19:36 UTC, OfficialEsco approved these changes

2021-08-24 19:41 UTC, merged