Fixes microsoft#21219 + some improvements
Trenly/winget-pkgs pull request #24
Opened 2021-09-13 15:22 UTC by vedantmgoyal2009

Fixes microsoft#21219

2021-09-13 15:45 UTC, vedantmgoyal2009 commented
@OfficialEsco Please look at **automatic architecture detection** and **automatic installer type detection** part. I will find a way for detecting inno, nullsoft, burn installer types and would implement it in future.

2021-09-13 15:45 UTC, Trenly requested changes

2021-09-13 15:45 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
I don't think this is valid. It would fail on installers like:
```
Installers:
- Architecture: x86
  InstallerUrl: https://launchpadlibrarian.net/509318994/armagetronad-0.2.9.1.0.win32.exe
  InstallerSha256: 96389283B7FA5944AB01BD7B324B48188796026EA57936042AADAE3078384F0A
```

2021-09-13 15:46 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
Why?

2021-09-13 15:48 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
![image](https://user-images.githubusercontent.com/83997633/133115553-2bea3794-b0b7-4ea7-8a1a-df263f7212a9.png)

2021-09-13 15:49 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
> Why?

It would detect the `arm` in the installer URL even though it is part of the package name and not indicative of the architecture

2021-09-13 15:52 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
Yes, I realize that the win32 is triggered first; But if you look at the edit I made to the original URL, then it would falsely trigger.

We can't assume that all URL's will follow that order. Consider a package named `Pub.Bladex64`. If it was an `arm` application and had the url `https://download.pub.com/app/Bladex64.arm.exe` then it would be incorrectly detected as an x64 app and not an arm app

2021-09-13 15:53 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
So, can we detect them using `$script:dest`

2021-09-13 16:10 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
@Trenly Done. I have made a better logic which when there are conflicts while checking installer architecture, it won't assign any value to `$architecture`

2021-09-13 21:24 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
> @Trenly Done. I have made a better logic which when there are conflicts while checking installer architecture, it won't assign any value to `$architecture`

This logic still suffers from the same deficiency that if the Installer URL has `arm` anywhere in it and doesn't mention any other architectures, it would still incorrectly detect the architecture. 

As an example, `https://download.armygame.com/files/armygame.exe`. This would trigger as an arm file, even if it is an x64 or x86 package. Even if you go with just the destination file `armygame.exe`, it will still detect in incorrectly.

2021-09-14 07:58 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
Hmm, need to work more to detect installer type

2021-09-14 08:00 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64'))) { $architecture = 'arm' }
One thing to confirm is that the installer type detection is fine?

2021-09-14 09:18 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +            $checkForArm = ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64')))
What if the URL contains x64_x86?
You could also add -x64, -x86, -arm, -arm64 for detection.
as long as you use contains x64, x86, arm, arm64 it will be very prone to false positive matching (mainly the arm part tho)

2021-09-14 09:18 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +            elseif ($script:dest.EndsWith('zip','CurrentCultureIgnoreCase')) { $InstallerType = 'zip' }
This is fine, i don't see a reason how this can cause a issue/false positive other than the url not ending with one of those

2021-09-14 09:28 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +            $checkForArm = ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64')))
Also just remembered /win32/ in the url does not always define x86, sometimes it means "windows", just like a win32 app in the Microsoft Store means desktop app.

2021-09-14 09:50 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            elseif ($script:dest.EndsWith('zip','CurrentCultureIgnoreCase')) { $InstallerType = 'zip' }
That's why I have compared it with the file name. 😀

2021-09-14 09:59 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            $checkForArm = ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64')))
> What if the URL contains x64_x86?

If you see the next 4-5 lines, you will notice that if there are multiple conditions matching, it won't assign any value to $architecture.

> You could also add -x64, -x86, -arm, -arm64 for detection.
> as long as you use contains x64, x86, arm, arm64 it will be very prone to false positive matching (mainly the arm part tho)

Ok, actually I have copied the logic from wingetcreate. Will change them to match `-x86` instead of `x86`

2021-09-14 13:37 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +            $checkForArm = ($InstallerUrl.Contains('arm') -and -not ($InstallerUrl.Contains('arm64') -or $InstallerUrl.Contains('aarch64')))
Tbh i would expect wingetcreate to use a smarter logic based on the executable, maybe they are running 2 checks? Or i just over estimated the logic… eitherway the false positive is off the charts when doing `wingetcreate update`…

2021-09-14 13:39 UTC, OfficialEsco commented on Tools/YamlCreate.ps1
> +            elseif ($script:dest.EndsWith('zip','CurrentCultureIgnoreCase')) { $InstallerType = 'zip' }
I did actually see that which is one of the reasons it would be safe… however my brain most have goldfished mid review 🤦‍♂️

2021-09-14 14:03 UTC, Trenly commented
Wingetcreate actually uses the `\b` specifiers for arm, which match word boundaries such as a period, hyphen, space, etc. I would suggest using `-match` with a regex string rather than `.Contains`

2021-09-17 06:37 UTC, closed without merging