SignatureSha256 and PackageFamilyName
Trenly/winget-pkgs pull request #5
Opened 2021-08-06 21:47 UTC by OfficialEsco

Resolves https://github.com/microsoft/winget-pkgs/issues/24066

2021-08-06 21:48 UTC, OfficialEsco commented
@vedantmgoyal2009

2021-08-07 02:08 UTC, vedantmgoyal2009 commented
Thanks, now I will add some more things. Actually, I don't know about YamlParsing which is why I could not proceed.

2021-08-07 02:15 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +            if (Get-Command 'winget.exe' -ErrorAction SilentlyContinue) { $SignatureSha256 = winget hash -m $dest | Select-String -Pattern "SignatureSha256:" | ConvertFrom-String; if ($SignatureSha25
Can't we add a condition like this?
```
if (($dest.EndsWith('appx') -or $dest.EndsWith('msix') -or $dest.EndsWith('appxbundle') -or $dest.EndsWith('msixbundle')) -and Get-Command 'winget.exe' -ErrorAction SilentlyContinue)  { 
winget hash -m $dest | Select-String -Pattern "SignatureSha256:" | ConvertFrom-String
if ($SignatureSha256.P2) { $SignatureSha256 = $SignatureSha256.P2.ToUpper() }
}
```

2021-08-07 02:16 UTC, vedantmgoyal2009 commented
Once this will get merged, I will do some more chnages. Thanks for this. I do not know about YamlParsing, so I couldn't proceed.

2021-08-07 05:24 UTC, vedantmgoyal2009 requested changes
If we are checking the same condition, why two times...

2021-08-07 05:24 UTC, vedantmgoyal2009 commented on Tools/YamlCreate.ps1
> +
```suggestion
    if ($InstallerType -ieq 'msix' -or $InstallerType -ieq 'appx') {
        if ([string]::IsNullOrWhiteSpace($SignatureSha256)) {
            do {
                Write-Host
                Write-Host -ForegroundColor 'Yellow' -Object '[Recommended] Enter the installer SignatureSha256'
                $SignatureSha256 = Read-Host -Prompt 'SignatureSha256' | TrimString
            } while (-not [string]::IsNullOrWhiteSpace($SignatureSha256) -and ($SignatureSha256 -notmatch $InstallerSchema.definitions.Installer.properties.SignatureSha256.pattern))
        }
        do {
            Write-Host
            Write-Host -ForegroundColor 'Yellow' -Object '[Recommended] Enter the installer PackageFamilyName'
            $PackageFamilyName = Read-Host -Prompt 'PackageFamilyName' | TrimString
        } while (-not [string]::IsNullOrWhiteSpace($PackageFamilyName) -and ($PackageFamilyName.Length -gt $InstallerSchema.definitions.PackageFamilyName.maxLength))
}

```

2021-08-07 13:35 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            if (Get-Command 'winget.exe' -ErrorAction SilentlyContinue) { $SignatureSha256 = winget hash -m $dest | Select-String -Pattern "SignatureSha256:" | ConvertFrom-String; if ($SignatureSha25
I’m not sure. If I’m not mistaken, the reason we want to check regardless of the file extension is that some msix installers can be packaged inside an exe wrapper

2021-08-07 13:36 UTC, Trenly approved these changes

2021-08-07 13:37 UTC, merged