Ensure file names are valid before saving
Trenly/winget-pkgs pull request #85
Opened 2021-10-08 18:44 UTC by Trenly

* Resolves #84 

@jedieaston @OfficialEsco @vedantmgoyal2009

I think this should work. I did some light testing on my own machine. If you could please review and test this quite carefully, this is one of the core parts of the script

URL Known to cause issues previously - https://pinyin.thunisoft.com/webapi/v1/setup/downloadSetup?setupid=21f0e88683894ebcb440759c5aa25c47&filename=HuayuPY-V7.2.0.213.exe

2021-10-08 19:28 UTC, jedieaston requested changes
Typo. 

BTW: Do you have a test link we can use that'll trigger the invalid extension logic?

2021-10-08 19:28 UTC, jedieaston commented on Tools/YamlCreate.ps1
> +# Checks a file name for validite and returns a boolean value
```suggestion
# Checks a file name for validity and returns a boolean value
```

2021-10-09 00:21 UTC, jedieaston approved these changes
Works well for me.

2021-10-09 01:27 UTC, Trenly commented
> Typo.
> 
> BTW: Do you have a test link we can use that'll trigger the invalid extension logic?

I was able to find one that caused an error - https://static.getaether.net/Releases/Aether-2.0.0-dev.15/2011262249.19338c93/win/Aether-Setup-2.0.0-dev.15%2B2011262249.19338c93.exe

Should be fixed with the latest push

2021-10-09 16:05 UTC, jedieaston commented on Tools/YamlCreate.ps1
> +            $download = Invoke-WebRequest -Uri $_NewInstaller['InstallerUrl'] -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome -DisableKeepAlive -TimeoutSec 30 -UseBasicParsing
This probably doesn't matter, but `[Microsoft.PowerShell.Commands.PSUserAgent]::Chrome` makes Invoke-WebRequest use the UserAgent for Chrome 7.0, which is 12 years old. I wonder if it would be better to use the winget user agent ("winget/1.0")

2021-10-09 16:08 UTC, Trenly commented on Tools/YamlCreate.ps1
> +            $download = Invoke-WebRequest -Uri $_NewInstaller['InstallerUrl'] -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome -DisableKeepAlive -TimeoutSec 30 -UseBasicParsing
Hmm. I can try it; I believe the issue was that sites don’t honor redirects when the user agent is the default powershell agent. Do you know if using the firefox agent is any newer?

2021-10-09 16:21 UTC, Trenly commented
> Can't we simply rename as {PackageIdentifier}.{PackageVersion}.{extension}
> 
> Reference: [microsoft#29454 (comment)](https://github.com/microsoft/winget-pkgs/pull/29454#issuecomment-934427931)

Technically, yes, but then that operates under the assumption that we can actually get the extension from the URL, which may not always be possible. 

By downloading the binary without saving it, we can see if the web server has specified the file name. If the name is specified, we should use that name. If we didn’t use that name, all of the automatic architecture checking would never happen or it would need to be reworked. If the name isn’t specified, or the name the server provided isn’t valid, that is when we should fall back to the PackageIdentifier.PackageVersion.extension.

However, even with that fallback, we can’t guarantee that a file extension was provided. We can try getting it from the provided file name, but it might not exist there. So, we can try getting it from the URL; if that doesn’t work, then we have to use our own extension. We could technically not have an extension, but having a last case extension makes it so users can better understand what the files in their temp directory are if they choose to save them

2021-10-09 16:24 UTC, vedantmgoyal2009 commented
Off-topic, is Moniker unknown?
![image](https://user-images.githubusercontent.com/83997633/136666463-1bd7715a-7c6d-4321-b2ad-5a71d20da2d4.png)

2021-10-09 16:40 UTC, jedieaston commented on Tools/YamlCreate.ps1
> +            $download = Invoke-WebRequest -Uri $_NewInstaller['InstallerUrl'] -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome -DisableKeepAlive -TimeoutSec 30 -UseBasicParsing
The Firefox agent is about as old (4.0 was released in 2011). See [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.psuseragent?view=powershellsdk-7.0.0) for more information.

That function returns a string though, maybe it would be best to just have a variable somewhere (`$userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"`) and use it wherever we use iwr.

2021-10-09 16:42 UTC, jedieaston commented
Moniker is only valid in files that are of ManifestType `defaultLocale` or `singleton`. The most likely reason for that error is that you have a file of type `locale` that has a Moniker in it. (In fact, the only difference between `defaultLocale` and `locale` is the Moniker field).

2021-10-09 16:45 UTC, Trenly commented
> Moniker is only valid in files that are of ManifestType `defaultLocale` or `singleton`. The most likely reason for that error is that you have a file of type `locale` that has a Moniker in it. (In fact, the only difference between `defaultLocale` and `locale` is the Moniker field).

Makes sense! I’ll update the logic to remove moniker when manifest type is locale

2021-10-10 18:05 UTC, vedantmgoyal2009 commented
I guess you should lower the limit of the message. (8 to 128 characters would be fine, I think 🤔)
![image](https://user-images.githubusercontent.com/83997633/136707896-fbb8a96c-6308-4759-a0c4-bce7cc187a26.png)

2021-10-11 01:01 UTC, jedieaston commented
240 characters (a tweet) should be enough? I think if you're going to make it as low as 128 characters, you should pop the link up to them to go and edit it (`gh pr create` prints it to stdout if you can snag it that way, or else calculate it?). 

Explaining why is important, at least to me (I usually assume Levvie or Esco or y'all know what you're doing, but if someone that doesn't contribute that often wants to nuke an entire ID, they should at least explain in the PR if not open an issue about it).

2021-10-11 12:15 UTC, jedieaston commented
The REST schema does, I must've gotten them mixed up.

2021-10-11 20:14 UTC, OfficialEsco commented
I only work with fields that are in the current JSON Schema, all our fields are in the Schema. If they don't work in the current client but is in the Schema and the bot approved them then that is not our problem, the client will get support for it and those fields will be filled.

2021-10-12 13:47 UTC, merged